language: php
php:
  - 8.1
  - 8.0
  - 7.1

before_script:
 - composer install

script: 
  - mkdir -p build/logs
  - vendor/bin/phpunit -c ./phpunit.xml --coverage-clover build/logs/clover.xml ./tests

after_script:
 - wget https://scrutinizer-ci.com/ocular.phar
 - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

 after_success:
  - travis_retry php vendor/bin/php-coveralls -v